### ISSUE TITLE
test cases fix

### ISSUE THREAD

**Issue by jul3x** [SpiritStudio/VehiclesEvolution#28]

**Comment by jul3x** [comment]
On branch feature/fixes there is travis-ci integration. Tests on computer are failed, but also on remote machine there is an error:

Failed to open X11 display; make sure the DISPLAY environment variable is set correctly

**Comment by danielm1405** [comment]
do tests build no your computer?

**Comment by jul3x** [comment]
@danielm1405 yes

**Comment by danielm1405** [comment]
which version of box2d do you use?

**Comment by jul3x** [comment]
2.3.1

**Comment by danielm1405** [comment]
tests build on travis (they still fail on both travis and local computer)

**Comment by jul3x** [comment]
everything passes now
